# SQL Subqueries - Lab

## Introduction

Now that you've seen how subqueries work, it's time to get some practice writing them! Not all of the queries will require subqueries, but all will be a bit more complex and require some thought and review about aggregates, grouping, ordering, filtering, joins and subqueries. Good luck!  

## Objectives

You will be able to:

* Write subqueries to decompose complex queries

## CRM Database Schema

Once again, here's the schema for the CRM database you'll continue to practice with.

<img src="images/Database-Schema.png" width="600">

## Connect to the Database

As usual, start by importing the necessary packages and connecting to the database **data.sqlite**.

In [1]:
#Your code here; import the necessary packages
import pandas as pd
import sqlite3

In [2]:
#Your code here; create the connection and cursor
conn = sqlite3.connect('data.sqlite')
c = conn.cursor()

## Write an Equivalent Query using a Subquery

```SQL
select customerNumber,
       contactLastName,
       contactFirstName
       from customers
       join orders 
       using(customerNumber)
       where orderDate = '2003-01-31';
```

In [3]:
#Your code here; use a subquery. No join will be necessary.
c.execute("""SELECT customerNumber,
                    contactLastName,
                    contactFirstName
                FROM customers
                WHERE customerNumber in (SELECT customerNumber FROM orders WHERE orderDate = '2003-01-31')""")
df = pd.DataFrame(c.fetchall())
df.columns = [x[0] for x in c.description]
df

  customerNumber contactLastName contactFirstName
0            141          Freyre           Diego

## Select the Total Number of Orders for Each Product Name

Sort the results by the total number of items sold for that product.

In [4]:
#Your code here
c.execute("""SELECT productName,
                    COUNT(orderNumber)
                FROM orderdetails od
                JOIN products p USING(productCode)
                GROUP BY od.productCode""")
df = pd.DataFrame(c.fetchall())
df.columns = [x[0] for x in c.description]
df.head()

                             productName  COUNT(orderNumber)
0  1969 Harley Davidson Ultimate Chopper                  28
1               1952 Alpine Renault 1300                  28
2                  1996 Moto Guzzi 1100i                  28
3   2003 Harley-Davidson Eagle Drag Bike                  28
4                    1972 Alfa Romeo GTA                  28

## Select the Product Name and the  Total Number of People Who Have Ordered Each Product

Sort the results in descending order.

In [5]:
#Your code here
c.execute("""SELECT productName,
                    COUNT(orderNumber)
                FROM products
                LEFT JOIN orderdetails USING(productCode)
                GROUP BY productCode
                ORDER BY productName
                """)
df = pd.DataFrame(c.fetchall())
df.columns = [x[0] for x in c.description]
df.head()

                           productName  COUNT(orderNumber)
0  18th Century Vintage Horse Carriage                  28
1                18th century schooner                  27
2               1900s Vintage Bi-Plane                  28
3              1900s Vintage Tri-Plane                  28
4                    1903 Ford Model A                  27

## Select the Employee Number, Office Code, City (of the office), and Name (First and Last) of those Employees who Sold Products that Have Been Ordered by Less Then 20 people.

This problem is a bit tougher. To start, think about how you might break the problem up. Be sure that your results only list each employee once.

In [6]:
c.execute("""SELECT *, 
                    COUNT(DISTINCT customerNumber) as poo
                FROM products
                JOIN orderdetails USING(productCode)
                JOIN orders USING(orderNumber)
                GROUP BY productCode
                ORDER BY poo DESC
                """)
df = pd.DataFrame(c.fetchall())
df.columns = [x[0] for x in c.description]
df

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP,orderNumber,quantityOrdered,priceEach,orderLineNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber,poo
0,S18_3232,1992 Ferrari 360 Spider red,Classic Cars,1:18,Unimax Art Galleries,"his replica features opening doors, superb det...",8347,77.90,169.34,10425,28,140.55,8,2005-05-31,2005-06-07,,In Process,,119,40
1,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30,10424,50,201.44,6,2005-05-31,2005-06-08,,In Process,,141,27
2,S10_4757,1972 Alfa Romeo GTA,Classic Cars,1:10,Motor City Art Classics,Features include: Turnable front wheels; steer...,3252,85.68,136.00,10414,49,114.24,3,2005-05-06,2005-05-13,,On Hold,Customer credit limit exceeded. Will ship when...,362,27
3,S18_2957,1934 Ford V8 Coupe,Vintage Cars,1:18,Min Lin Diecast,"Chrome Trim, Chrome Grille, Opening Hood, Open...",5649,34.35,62.46,10423,31,56.21,3,2005-05-30,2005-06-05,,In Process,,314,27
4,S72_1253,Boeing X-32A JSF,Planes,1:72,Motor City Art Classics,"10"" Wingspan with retractable landing gears.Co...",4857,32.77,49.66,10415,42,43.20,3,2005-05-09,2005-05-20,2005-05-12,Disputed,Customer claims the scales of the models don't...,471,27
5,S10_1678,1969 Harley Davidson Ultimate Chopper,Motorcycles,1:10,Min Lin Diecast,"This replica features working kickstand, front...",7933,48.81,95.70,10417,66,79.43,2,2005-05-13,2005-05-19,2005-05-19,Disputed,Customer doesn't like the colors and precision...,141,26
6,S10_2016,1996 Moto Guzzi 1100i,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94,10417,45,116.56,5,2005-05-13,2005-05-19,2005-05-19,Disputed,Customer doesn't like the colors and precision...,141,26
7,S18_1662,1980s Black Hawk Helicopter,Planes,1:18,Red Start Diecast,1:18 scale replica of actual Army's UH-60L BLA...,5330,77.27,157.69,10416,24,129.31,14,2005-05-10,2005-05-16,2005-05-14,Shipped,,386,26
8,S18_1984,1995 Honda Civic,Classic Cars,1:18,Min Lin Diecast,"This model features, opening hood, opening doo...",9772,93.89,142.25,10419,34,133.72,4,2005-05-17,2005-05-28,2005-05-19,Shipped,,382,26
9,S18_2949,1913 Ford Model T Speedster,Vintage Cars,1:18,Carousel DieCast Legends,This 250 part reproduction includes moving han...,4189,60.78,101.31,10423,10,89.15,1,2005-05-30,2005-06-05,,In Process,,314,26
10,S18_3029,1999 Yamaha Speed Boat,Ships,1:18,Min Lin Diecast,Exact replica. Wood and Metal. Many extras inc...,4259,51.61,86.02,10414,44,77.42,1,2005-05-06,2005-05-13,,On Hold,Customer credit limit exceeded. Will ship when...,362,26
11,S18_3136,18th Century Vintage Horse Carriage,Vintage Cars,1:18,Red Start Diecast,Hand crafted diecast-like metal horse carriage...,5992,60.74,104.72,10423,21,98.44,2,2005-05-30,2005-06-05,,In Process,,314,26
12,S18_3856,1941 Chevrolet Special Deluxe Cabriolet,Vintage Cars,1:18,Exoto Designs,"Features opening hood, opening doors, opening ...",2378,64.58,105.87,10415,51,86.81,5,2005-05-09,2005-05-20,2005-05-12,Disputed,Customer claims the scales of the models don't...,471,26
13,S24_2841,1900s Vintage Bi-Plane,Planes,1:24,Autoart Studio Design,Hand crafted diecast-like metal bi-plane is re...,5942,34.25,68.51,10415,21,60.97,1,2005-05-09,2005-05-20,2005-05-12,Disputed,Customer claims the scales of the models don't...,471,26
14,S24_3420,1937 Horch 930V Limousine,Vintage Cars,1:24,Autoart Studio Design,"Features opening hood, opening doors, opening ...",2902,26.30,65.75,10415,18,59.83,2,2005-05-09,2005-05-20,2005-05-12,Disputed,Customer claims the scales of the models don't...,471,26
15,S24_3816,1940 Ford Delivery Sedan,Vintage Cars,1:24,Carousel DieCast Legends,"Chrome Trim, Chrome Grille, Opening Hood, Open...",6621,48.64,83.86,10414,51,72.96,2,2005-05-06,2005-05-13,,On Hold,Customer credit limit exceeded. Will ship when...,362,26
16,S24_3949,Corsair F4U ( Bird Cage),Planes,1:24,Second Gear Diecast,Has retractable wheels and comes with a stand....,6812,29.34,68.24,10416,18,64.83,13,2005-05-10,2005-05-16,2005-05-14,Shipped,,386,26
17,S700_2047,HMS Bounty,Ships,1:700,Unimax Art Galleries,Measures 30 inches Long x 27 1/2 inches High x...,3501,39.83,90.52,10415,32,73.32,4,2005-05-09,2005-05-20,2005-05-12,Disputed,Customer claims the scales of the models don't...,471,26
18,S700_4002,American Airlines: MD-11S,Planes,1:700,Second Gear Diecast,Polished finish. Exact replia with official lo...,8820,36.27,74.03,10416,43,63.67,12,2005-05-10,2005-05-16,2005-05-14,Shipped,,386,26
19,S10_4698,2003 Harley-Davidson Eagle Drag Bike,Motorcycles,1:10,Red Start Diecast,"Model features, official Harley Davidson logos...",5582,91.02,193.66,10417,56,162.67,4,2005-05-13,2005-05-19,2005-05-19,Disputed,Customer doesn't like the colors and precision...,141,25
20,S10_4962,1962 LanciaA Delta 16V,Classic Cars,1:10,Second Gear Diecast,Features include: Turnable front wheels; steer...,6791,103.42,147.74,10425,38,131.49,12,2005-05-31,2005-06-07,,In Process,,119,25
21,S12_2823,2002 Suzuki XREO,Motorcycles,1:12,Unimax Art Galleries,"Official logos and insignias, saddle bags loca...",9997,66.27,150.62,10417,21,144.60,1,2005-05-13,2005-05-19,2005-05-19,Disputed,Customer doesn't like the colors and precision...,141,25
22,S18_1097,1940 Ford Pickup Truck,Trucks and Buses,1:18,Studio M Art Models,"This model features soft rubber tires, working...",2613,58.33,116.67,10424,54,108.50,5,2005-05-31,2005-06-08,,In Process,,141,25
23,S18_1129,1993 Mazda RX-7,Classic Cars,1:18,Highway 66 Mini Classics,"This model features, opening hood, opening doo...",3975,83.51,141.54,10419,38,117.48,5,2005-05-17,2005-05-28,2005-05-19,Shipped,,382,25
24,S18_1342,1937 Lincoln Berline,Vintage Cars,1:18,Motor City Art Classics,"Features opening engine cover, doors, trunk, a...",8693,60.62,102.74,10422,51,91.44,2,2005-05-30,2005-06-11,,In Process,,157,25
25,S18_1367,1936 Mercedes-Benz 500K Special Roadster,Vintage Cars,1:18,Studio M Art Models,This 1:18 scale replica is constructed of heav...,8635,24.26,53.91,10422,25,47.44,1,2005-05-30,2005-06-11,,In Process,,157,25
26,S18_1889,1948 Porsche 356-A Roadster,Classic Cars,1:18,Gearbox Collectibles,This precision die-cast replica features openi...,8826,53.90,77.00,10419,39,67.76,9,2005-05-17,2005-05-28,2005-05-19,Shipped,,382,25
27,S18_2625,1936 Harley Davidson El Knucklehead,Motorcycles,1:18,Welly Diecast Productions,Intricately detailed with chrome accents and t...,4357,24.23,60.57,10417,36,58.75,6,2005-05-13,2005-05-19,2005-05-19,Disputed,Customer doesn't like the colors and precision...,141,25
28,S18_4600,1940s Ford truck,Trucks and Buses,1:18,Motor City Art Classics,This 1940s Ford Pick-Up truck is re-created in...,3128,84.76,121.08,10425,38,107.76,13,2005-05-31,2005-06-07,,In Process,,119,25
29,S24_1578,1997 BMW R 1100 S,Motorcycles,1:24,Autoart Studio Design,Detailed scale replica with working suspension...,7003,60.86,112.70,10417,35,109.32,3,2005-05-13,2005-05-19,2005-05-19,Disputed,Customer doesn't like the colors and precision...,141,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,S700_1938,The Mayflower,Ships,1:700,Studio M Art Models,Measures 31 1/2 inches Long x 25 1/2 inches Hi...,737,43.30,86.61,10414,34,74.48,13,2005-05-06,2005-05-13,,On Hold,Customer credit limit exceeded. Will ship when...,362,22
80,S700_2824,1982 Camaro Z28,Classic Cars,1:18,Carousel DieCast Legends,Features include opening and closing doors. Co...,6934,46.53,101.15,10424,46,85.98,1,2005-05-31,2005-06-08,,In Process,,141,22
81,S700_3505,The Titanic,Ships,1:700,Carousel DieCast Legends,"Completed model measures 19 1/2 inches long, 9...",1956,51.09,100.17,10414,28,84.14,7,2005-05-06,2005-05-13,,On Hold,Customer credit limit exceeded. Will ship when...,362,22
82,S12_4473,1957 Chevy Pickup,Trucks and Buses,1:12,Exoto Designs,"1:12 scale die-cast about 20"" long Hood opens,...",6125,55.70,118.50,10425,33,95.99,4,2005-05-31,2005-06-07,,In Process,,119,21
83,S18_2238,1998 Chrysler Plymouth Prowler,Classic Cars,1:18,Gearbox Collectibles,Turnable front wheels; steering function; deta...,4724,101.51,163.73,10425,28,147.36,3,2005-05-31,2005-06-07,,In Process,,119,21
84,S18_2795,1928 Mercedes-Benz SSK,Vintage Cars,1:18,Gearbox Collectibles,This 1:18 replica features grille-mounted chro...,548,72.56,168.75,10421,35,167.06,1,2005-05-29,2005-06-06,,In Process,Custom shipping instructions were sent to ware...,124,21
85,S18_2870,1999 Indy 500 Monte Carlo SS,Classic Cars,1:18,Red Start Diecast,Features include opening and closing doors. Co...,8164,56.76,132.00,10419,55,116.16,2,2005-05-17,2005-05-28,2005-05-19,Shipped,,382,21
86,S18_3140,1903 Ford Model A,Vintage Cars,1:18,Unimax Art Galleries,"Features opening trunk, working steering system",3913,68.30,136.59,10414,41,128.39,12,2005-05-06,2005-05-13,,On Hold,Customer credit limit exceeded. Will ship when...,362,21
87,S18_3278,1969 Dodge Super Bee,Classic Cars,1:18,Min Lin Diecast,"This replica features opening doors, superb de...",1917,49.05,80.41,10418,16,70.76,2,2005-05-16,2005-05-24,2005-05-20,Shipped,,412,21
88,S18_3685,1948 Porsche Type 356 Roadster,Classic Cars,1:18,Gearbox Collectibles,This model features working front and rear sus...,8990,62.16,141.28,10419,43,114.44,3,2005-05-17,2005-05-28,2005-05-19,Shipped,,382,21
89,S18_3782,1957 Vespa GS150,Motorcycles,1:18,Studio M Art Models,"Features rotating wheels , working kick stand....",7689,32.95,62.17,10418,33,56.57,5,2005-05-16,2005-05-24,2005-05-20,Shipped,,412,21
90,S18_4027,1970 Triumph Spitfire,Classic Cars,1:18,Min Lin Diecast,Features include opening and closing doors. Co...,5545,91.92,143.62,10413,49,133.57,5,2005-05-05,2005-05-14,2005-05-09,Shipped,Customer requested that DHL is used for this s...,175,21
91,S18_4721,1957 Corvette Convertible,Classic Cars,1:18,Classic Metal Creations,1957 die cast Corvette Convertible in Roman Re...,1249,69.93,148.80,10418,28,120.53,4,2005-05-16,2005-05-24,2005-05-20,Shipped,,412,21
92,S24_1628,1966 Shelby Cobra 427 S/C,Classic Cars,1:24,Carousel DieCast Legends,This diecast model of the 1966 Shelby Cobra 42...,8197,29.18,50.31,10420,37,48.80,13,2005-05-29,2005-06-07,,In Process,,282,21
93,S24_2300,1962 Volkswagen Microbus,Trucks and Buses,1:24,Autoart Studio Design,This 1:18 scale die cast replica of the 1962 M...,2327,61.34,127.79,10425,49,127.79,9,2005-05-31,2005-06-07,,In Process,,119,21
94,S24_2972,1982 Lamborghini Diablo,Classic Cars,1:24,Second Gear Diecast,"This replica features opening doors, superb de...",7723,16.24,37.76,10419,15,32.10,7,2005-05-17,2005-05-28,2005-05-19,Shipped,,382,21
95,S24_3969,1936 Mercedes Benz 500k Roadster,Vintage Cars,1:24,Red Start Diecast,This model features grille-mounted chrome horn...,2081,21.75,41.03,10420,15,35.29,3,2005-05-29,2005-06-07,,In Process,,282,21
96,S32_2206,1982 Ducati 996 R,Motorcycles,1:32,Gearbox Collectibles,"Features rotating wheels , working kick stand....",9241,24.14,40.23,10418,43,36.61,6,2005-05-16,2005-05-24,2005-05-20,Shipped,,412,21
97,S18_3259,Collectable Wooden Train,Trains,1:18,Carousel DieCast Legends,Hand crafted wooden toy train set is in about ...,6450,67.56,100.84,10414,48,85.71,14,2005-05-06,2005-05-13,,On Hold,Customer credit limit exceeded. Will ship when...,362,20
98,S18_3482,1976 Ford Gran Torino,Classic Cars,1:18,Gearbox Collectibles,"Highly detailed 1976 Ford Gran Torino ""Starsky...",9127,73.49,146.99,10418,27,139.64,1,2005-05-16,2005-05-24,2005-05-20,Shipped,,412,20
99,S18_4933,1957 Ford Thunderbird,Classic Cars,1:18,Studio M Art Models,"This 1:18 scale precision die-cast replica, wi...",3209,34.21,71.27,10420,36,68.42,7,2005-05-29,2005-06-07,,In Process,,282,20
100,S24_1046,1970 Chevy Chevelle SS 454,Classic Cars,1:24,Unimax Art Galleries,"This model features rotating wheels, working s...",1005,49.24,73.49,10420,60,60.26,11,2005-05-29,2005-06-07,,In Process,,282,20
101,S24_1444,1970 Dodge Coronet,Classic Cars,1:24,Highway 66 Mini Classics,"1:24 scale die-cast about 18"" long doors open,...",4074,32.37,57.80,10425,55,53.75,1,2005-05-31,2005-06-07,,In Process,,119,20
102,S24_4048,1992 Porsche Cayenne Turbo Silver,Classic Cars,1:24,Exoto Designs,"This replica features opening doors, superb de...",6582,69.78,118.28,10412,31,108.82,1,2005-05-03,2005-05-13,2005-05-05,Shipped,,141,20
103,S32_2509,1954 Greyhound Scenicruiser,Trucks and Buses,1:32,Classic Metal Creations,"Model features bi-level seating, 50 windows, s...",2874,25.98,54.11,10425,11,50.32,6,2005-05-31,2005-06-07,,In Process,,119,20
104,S24_2840,1958 Chevy Corvette Limited Edition,Classic Cars,1:24,Carousel DieCast Legends,The operating parts of this 1958 Chevy Corvett...,2542,15.91,35.36,10425,31,31.82,5,2005-05-31,2005-06-07,,In Process,,119,19
105,S24_2766,1949 Jaguar XK 120,Classic Cars,1:24,Classic Metal Creations,Precision-engineered from original Jaguar spec...,2350,47.25,90.87,10420,39,76.33,9,2005-05-29,2005-06-07,,In Process,,282,18
106,S24_2887,1952 Citroen-15CV,Classic Cars,1:24,Exoto Designs,Precision crafted hand-assembled 1:18 scale re...,1452,72.82,117.44,10420,55,115.09,8,2005-05-29,2005-06-07,,In Process,,282,18
107,S24_3191,1969 Chevrolet Camaro Z28,Classic Cars,1:24,Exoto Designs,1969 Z/28 Chevy Camaro 1:24 scale replica. The...,4695,50.51,85.61,10420,35,77.05,10,2005-05-29,2005-06-07,,In Process,,282,18
108,S24_3432,2002 Chevy Corvette,Classic Cars,1:24,Gearbox Collectibles,The operating parts of this limited edition Di...,9446,62.11,107.08,10420,26,104.94,12,2005-05-29,2005-06-07,,In Process,,282,18

In [7]:
#Your code here
c.execute("""SELECT DISTINCT employeeNumber,
                    officeCode,
                    o.city,
                    e.firstName,
                    e.lastName
                FROM employees e
                JOIN offices o USING(officeCode)
                JOIN customers c ON e.employeeNumber = c.salesRepEmployeeNumber
                JOIN orders USING(customerNumber)
                JOIN orderdetails od USING(orderNumber)
                WHERE productCode IN (SELECT productCode
                                        FROM products
                                        JOIN orderdetails USING(productCode)
                                        JOIN orders USING(orderNumber)
                                        GROUP BY productCode
                                        HAVING COUNT(DISTINCT customerNumber)<=20)""")
df = pd.DataFrame(c.fetchall())
df.columns = [x[0] for x in c.description]
df

   employeeNumber officeCode           city firstName   lastName
0            1370          4          Paris    Gerard  Hernandez
1            1401          4          Paris    Pamela   Castillo
2            1621          5          Tokyo      Mami      Nishi
3            1501          7         London     Larry       Bott
4            1337          4          Paris      Loui     Bondur
5            1286          3            NYC  Foon Yue      Tseng
6            1166          1  San Francisco    Leslie   Thompson
7            1165          1  San Francisco    Leslie   Jennings
8            1612          6         Sydney     Peter      Marsh
9            1188          2         Boston     Julie   Firrelli
10           1611          6         Sydney      Andy     Fixter
11           1323          3            NYC    George     Vanauf
12           1702          4          Paris    Martin     Gerard
13           1504          7         London     Barry      Jones
14           1216          2         Boston     Steve  Patterson

## Select the Employee Number, Name (First and Last) and Number of Customers of Employees Whose Customers Have an Average Credit Limit of Over 15K

In [8]:
c.execute("""SELECT customerName, creditLimit 
                FROM customers 
                GROUP BY customerNumber
                HAVING AVG(creditLimit) > 15000
                ORDER BY creditLimit ASC""")
df = pd.DataFrame(c.fetchall())
df.columns = [x[0] for x in c.description]
df

                         customerName creditLimit
0               Diecast Classics Inc.   100600.00
1                       Mini Classics   102700.00
2             Dragon Souveniers, Ltd.   103800.00
3          Corrida Auto Replicas, Ltd   104600.00
4        Collectable Mini Designs Co.   105000.00
5            Corporate Gift Ideas Co.   105000.00
6             Anna's Decorations, Ltd   107800.00
7                   Kelly's Gift Shop   110000.00
8                  Amica Models & Co.   113000.00
9        Online Diecast Creations Co.   114200.00
10                  Land of Toys Inc.   114900.00
11            Scandinavian Gift Ideas   116400.00
12         Australian Collectors, Co.   117300.00
13                  La Rochelle Gifts   118200.00
14                      Rovelli Gifts   119600.00
15            Toms Spezialitäten, Ltd   120400.00
16               Heintze Collectables   120800.00
17                L'ordine Souveniers   121400.00
18               Marta's Replicas Co.   123700.00
19             Saveley & Henriot, Co.   123900.00
20                     AV Stores, Co.   136800.00
21                 Muscle Machine Inc   138500.00
22                    Vida Sport, Ltd   141300.00
23                  Atelier graphique    21000.00
24       Mini Gifts Distributors Ltd.   210500.00
25             Euro+ Shopping Channel   227600.00
26            Auto-Moto Classics Inc.    23000.00
27                       Royale Belge    23500.00
28                 Frau da Collezione    34800.00
29                    Microscale Inc.    39800.00
..                                ...         ...
67            Classic Gift Ideas, Inc    81100.00
68                 Reims Collectables    81100.00
69               Osaka Souveniers Co.    81200.00
70                    Cruz & Sons Co.    81500.00
71                 Baane Mini Imports    81700.00
72           Daedalus Designs Imports    82900.00
73           Danish Wholesale Imports    83400.00
74          La Corne D'abondance, Co.    84300.00
75                    Gift Depot Inc.    84300.00
76               Technics Stores Inc.    84600.00
77               Diecast Collectables    85100.00
78                   FunGiftIdeas.com    85800.00
79      Extreme Desk Decorations, Ltd    86800.00
80         Down Under Souveniers, Inc    88000.00
81  Royal Canadian Collectables, Ltd.    89600.00
82     Canadian Gift Exchange Network    90300.00
83            Oulu Toy Supplies, Inc.    90500.00
84                  Toys4GrownUps.com    90700.00
85              UK Collectables, Ltd.    92700.00
86          Souveniers And Things Co.    93300.00
87                  giftsbymail.co.uk    93900.00
88            Tokyo Collectables, Ltd    94400.00
89                Mini Creations Ltd.    94500.00
90                  Auto Canal+ Petit    95000.00
91          Norway Gifts By Mail, Co.    95100.00
92                   Super Scale Inc.    95400.00
93               Toys of Finland, Co.    96500.00
94                       Herkku Gifts    96800.00
95                   Handji Gifts& Co    97900.00
96                Suominen Souveniers    98800.00

[97 rows x 2 columns]

In [9]:
#Your code here
c.execute("""SELECT employeeNumber,
                    e.firstName,
                    e.lastName,
                    COUNT(DISTINCT customerNumber) as numOfCustomers
                FROM employees e
                JOIN customers c 
                    ON e.employeeNumber = c.salesRepEmployeeNumber

                GROUP BY employeeNumber, firstName, lastName
                HAVING AVG(creditLimit) > 15000
                ORDER BY employeeNumber""")
df = pd.DataFrame(c.fetchall())
df.columns = [x[0] for x in c.description]
df

   employeeNumber firstName   lastName  numOfCustomers
0            1165    Leslie   Jennings               6
1            1166    Leslie   Thompson               6
2            1188     Julie   Firrelli               6
3            1216     Steve  Patterson               6
4            1286  Foon Yue      Tseng               7
5            1323    George     Vanauf               8
6            1337      Loui     Bondur               6
7            1370    Gerard  Hernandez               7
8            1401    Pamela   Castillo              10
9            1501     Larry       Bott               8
10           1504     Barry      Jones               9
11           1611      Andy     Fixter               5
12           1612     Peter      Marsh               5
13           1621      Mami      Nishi               5
14           1702    Martin     Gerard               6

## Summary

In this lesson, you got to practice some more complex SQL queries, some of which required subqueries. There's still plenty more SQL to be had though; hope you've been enjoying some of these puzzles!